steps:
- name: 'ubuntu'
  id: 'step-Sec'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        echo "Hello, world! ${_SEC}" > file
        cat file
        no_failure_count=`cat file| grep "security" | wc -l`
        echo "is text security present $no_failure_count"
        if [ "$no_failure_count" -ge 1 ]; then 
        exit 0; 
        else 
        exit 255; 
        fi

substitutions:
    _SEC: "dummy"